overwrite: true
schema:
  - "http://localhost:4000"
documents:
  - "schema/*.gql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withComponent: false
      withHOC: false
      withHooks: true
      gqlImport: graphql.macro#gql
  src/generated/fragmentTypes.json:
    plugins:
      - fragment-matcher