overwrite: true
schema:
  - "schema/schema.gql"
documents:
  - "schema/query.gql"
  - "schema/fragment.gql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withComponent: false
      withHOC: false
      withHooks: true
      gqlImport: graphql.macro#gql
      apolloReactCommonImportFrom: "@apollo/client"
      apolloReactHooksImportFrom: "@apollo/client"
  src/generated/fragmentTypes.json:
    plugins:
      - fragment-matcher