fragment Endpoint on Endpoint {
  host
  port
}

fragment LabWithoutEndpoint on Lab {
  id
  endpoints {
    ...Endpoint
  }
  resources {
    ...ResourceWithTranslation
  }
}

fragment LabCategory on LabCategory {
  id
  name {
    ...Translation
  }
  labs {
    ...LabWithoutEndpoint
  }
}

fragment Practice on Practice {
  labCategories {
    ...LabCategory
  }
}

fragment LabInstance on LabInstance {
  lang
  name
  content
  endpoints {
    ...Endpoint
  }
}

fragment ResourceWithTranslation on ResourceWithTranslation {
  lang
  name
}

fragment Translation on Translation {
  lang
  text
}
