query Hello {
  hello
}

query Practices {
  practice {
    ...Practice
  }
}

query Lab($categoryId: String!, $labId: String!, $language: String) {
  lab(categoryId: $categoryId, labId: $labId, language: $language) {
    ...LabInstance
  }
}