name: Publish

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

jobs:
  Release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: npm install
      run: npm install
    - name: npm build
      run: GENERATE_SOURCEMAP=false npm run build

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r www.zip build

    - name: Upload builds to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: www.zip
        tag: ${{ github.ref }}
        asset_name: www.zip
        overwrite: true
